eqcorrscan/scripts/synth_detector.py, eqcorrscan/utils/Sfile_util.py
Sfile_util was relying on trailing space on pick line in sfiles, this is not always the case and is now accomodated.
=> Sfile_util bug-fix

.travis.yml, README.md, eqcorrscan/tests/__init__.py, eqcorrscan/tests/runtests.py, eqcorrscan/utils/Sfile_util.py, setup.py
Changes concerning travis builds and test set-up:
- Only incorporated import testing and S-file testing into travis build, needs more tests
- Build passing now.
=> Merge tests to master

eqcorrscan/core/lag_calc.py
Add cccsum and cc output to lag_calc
=> outputs ccsum

eqcorrscan/core/template_gen.py
=> Do not use picks without station or channel codes

eqcorrscan/utils/mag_calc.py
Modelled picks depend on hypocentral distance - this was set to epicentral distance - this patch now does this properly (hypo_dist = sqrt(sq(epi_dist) + sq(depth)))
=> syntax changes and do hypo_dist properly with depth

eqcorrscan/core/match_filter.py, eqcorrscan/utils/clustering.py
Also a minor fix to clustering.dist_mat_km.
=> Remove unnecessary condition from Template.__init__

eqcorrscan/core/subspace.py, eqcorrscan/doc/conf.py
Docs build fine locally after adding h5py to MOCK_MODULES.
=> patch subspace docs

eqcorrscan/__init__.py, eqcorrscan/core/match_filter.py, eqcorrscan/doc/intro.rst, eqcorrscan/tests/match_filter_test.py
This PR is to update the docs in the master branch, and contains no changes to code.  It does contain a change to a doctest to ensure tests (should) pass.
This will not constitute a patch release.
=> Update master docs and doctest fail

CHANGES.md, conftest.py, eqcorrscan/__init__.py, eqcorrscan/core/match_filter.py, eqcorrscan/doc/submodules/utils.correlate.rst, eqcorrscan/tests/correlate_test.py, eqcorrscan/tests/mag_calc_test.py, eqcorrscan/utils/clustering.py, eqcorrscan/utils/correlate.py, eqcorrscan/utils/mag_calc.py, setup.py
close issue # 119
Hey @calum-chamberlain and @cjhopp , I think this is able to merge. I would appreciate it if you could give it a good look-over to make sure I didn't do anything dumb in handling merge conflicts. We will see how the CI runs go...
=> Correlate refactor

eqcorrscan/doc/submodules/utils.correlate.rst, eqcorrscan/utils/correlate.py
Update the docs for correlate to include the equation used - closes #140 
Also need to build these docs on readthedocs and check that they work properly.
=> WIP: Update utils.correlate.rst

.circleci/config.yml, eqcorrscan/tutorials/get_geonet_events.py
Circleci is failing without any changes to our codes - possibly an issue/change up there?
This PR changes the image to a 3.5 image.  I can't recreate the failures locally.
=> Alter circleci set-up to allow network tests to run

eqcorrscan/core/match_filter.py
This PR simply add location codes to pick info from match-filter as requested by @emilyws1 in #176.
Closes #176
=> Add location code to picks in match-filter

eqcorrscan/core/template_gen.py
=> Remove excessive copying of data

CHANGES.md, eqcorrscan/__init__.py, eqcorrscan/core/match_filter.py, eqcorrscan/core/template_gen.py, eqcorrscan/lib/multi_corr.c, eqcorrscan/tests/match_filter_test.py, eqcorrscan/tests/pre_processing_test.py, eqcorrscan/utils/correlate.py, eqcorrscan/utils/pre_processing.py
Pre-processing pads with zeros before processing - processing can convert these to non-zero, which generates un-real correlations.
This PR tracks zeros added before processing and makes them revert to zeros after processing.
This needs a test.
=> Force zeros where there are no data

eqcorrscan/tests/match_filter_test.py, eqcorrscan/utils/archive_read.py, eqcorrscan/utils/catalog_to_dd.py, eqcorrscan/utils/catalog_utils.py, eqcorrscan/utils/despike.py, eqcorrscan/utils/findpeaks.py
Clean imports in utils functions.  Closes #218
=> Clean imports

eqcorrscan/doc/index.rst
@cjhopp pointed out that people call matched filtering template matching, so I added that term.
=> Add template-matching to docs

CHANGES.md, eqcorrscan/core/template_gen.py, eqcorrscan/tests/template_gen_test.py
This patches `template_gen` so that options `swin="P_all"` and `swin="S_all` download all channels as required by the method.
This closes #206 
~~- [x] Any new or changed features have are fully documented.~~
~~- [x] First time contributors have added your name to `CONTRIBUTORS.md`.~~
=> Patch all channel download

eqcorrscan/core/match_filter.py, eqcorrscan/doc/tutorials/matched-filter.rst, eqcorrscan/utils/pre_processing.py
Adds more explicit advice on how gaps are handled (#258), and that detections are not corrected for pre-pick (#255)
Closes #258 
Closes #255 
=> Update docs for pre-pick and gap handling

CHANGES.md, eqcorrscan/core/bright_lights.py, eqcorrscan/core/lag_calc.py, eqcorrscan/core/subspace.py, eqcorrscan/utils/correlate.py, eqcorrscan/utils/pre_processing.py
Catches KeyboardInterrupt in multiprocessing routines.
Closes #241 
~~- [x] Any new features or fixed regressions are be covered via new tests.~~
~~- [x] Any new or changed features have are fully documented.~~
=> Propagate KeyboardInterrupt errors

.travis.yml, appveyor.yml, requirements.txt
See notes @d-chambers made in [this issue](https://github.com/niosh-mining/obsplus/issues/33) - tests are failing because of changes in pytest.
=> Pin pytest to less than 4.0

.travis.yml, CHANGES.md, appveyor.yml, conftest.py, eqcorrscan/core/match_filter/matched_filter.py, requirements.txt
Add support/remove depreciated features for pytest 4.x
Closes #303 
This is related to [depreciations in 4.0](https://docs.pytest.org/en/latest/deprecations.html#pytest-namespace)
=> Remove pytest_namespace in conftest

CHANGES.md, eqcorrscan/core/match_filter/matched_filter.py
Adds warnings if data are not used because they don't fit in a chunk, and stops an error occurring when `daylong=True` and the data do not fit in the chunk.
Closes #291 
=> Warn when data are not used due to chunk size.

.circleci/config.yml, .travis.yml, CHANGES.md, appveyor.yml, eqcorrscan/core/lag_calc.py, eqcorrscan/core/match_filter/detection.py, eqcorrscan/core/match_filter/family.py, eqcorrscan/core/match_filter/party.py, eqcorrscan/core/match_filter/template.py, eqcorrscan/core/match_filter/tribe.py, eqcorrscan/tests/find_peaks_test.py, eqcorrscan/tests/lag_calc_test.py, eqcorrscan/tests/match_filter_test.py, eqcorrscan/tests/subspace_test.py, eqcorrscan/tests/template_gen_test.py, eqcorrscan/tests/tutorials_test.py, eqcorrscan/tutorials/lag_calc.py, eqcorrscan/utils/correlate.py, eqcorrscan/utils/plotting.py, eqcorrscan/utils/synth_seis.py
Refactors lag-calc to use the new correlation functions. These are faster, more memory efficient and more stable.  I also took the chance to clean up the lag_calc code a lot - as I get better at writing code, so hopefully the codebase will get cleaner!
#276 
=> Refactor lag calc

CHANGES.md, CONTRIBUTORS.md, eqcorrscan/core/lag_calc.py
Develop add plotdir to xcorr_pick_family function. I hope all things be true this time. thanks.
=> Develop add plotdir to xcorr_pick_family function

CHANGES.md, eqcorrscan/core/lag_calc.py, eqcorrscan/core/match_filter/family.py, eqcorrscan/core/match_filter/matched_filter.py, eqcorrscan/core/match_filter/party.py, eqcorrscan/core/match_filter/template.py, eqcorrscan/core/match_filter/tribe.py, eqcorrscan/core/template_gen.py, eqcorrscan/doc/tutorials/quick_start.ipynb, eqcorrscan/utils/plotting.py
Adds a standardised `plotdir` argument to:
- `core.template_gen.template_gen`,
- `core.matched_filter.match_filter.match_filter`,
- `core.matched_filter.family.lag_calc`
- `core.matched_filter.party.lag_calc`
- `core.matched_filter.template.construct`
- `core.matched_filter.template.detect`
- `core.matched_filter.tribe.detect`
- `core.matched_filter.tribe.client_detect`
- `core.matched_filter.tribe.construct`
This also adds some of the minor changes in #329.
#329 
=> Add plotdir throughout

CHANGES.md, eqcorrscan/core/lag_calc.py
save figure in specific folder 
- [* ] `develop` base branch selected?
- [*] This PR is not directly related to an existing issue (which has no PR yet).
- [ *] All tests still pass.
- [ *] Any new features or fixed regressions are be covered via new tests.
- [ *] Any new or changed features have are fully documented.
- [ *] Significant changes have been added to `CHANGES.md`.
=> just add plotdir to lag_calc.lag_calc function

eqcorrscan/core/match_filter/matched_filter.py, eqcorrscan/core/template_gen.py
=> correction some docs

eqcorrscan/core/match_filter/template.py
Now regex accept dash and upper/lower case letter.
#346
=> enhancement regex's patern in template.py

appveyor.yml
Pyproj changed API for 2.x and Obspy has some issues with it (which are fixed by [this pr](https://github.com/obspy/obspy/pull/2442)).
Not running tests in #340 
=> Attempt to fix failing CI tests

CHANGES.md, eqcorrscan/core/match_filter/family.py, eqcorrscan/core/match_filter/matched_filter.py, eqcorrscan/core/match_filter/party.py, eqcorrscan/core/match_filter/template.py, eqcorrscan/core/match_filter/tribe.py, eqcorrscan/core/template_gen.py, eqcorrscan/utils/plotting.py
It fix some issue in _match_filter_plot.
#339
=> fix cccsum_plot

eqcorrscan/utils/plotting.py
Put legend inside of main frame Just for beauty.
=> Put legend inside of main frame

eqcorrscan/utils/catalog_to_dd.py
Make the docs for `shift_len` more explicit.
It wasn't very clear that this was +/- the pick time before.
=> Make docs for shift_len more explicit.

CHANGES.md, eqcorrscan/tests/mag_calc_test.py, eqcorrscan/utils/mag_calc.py
- Code cleaned up and making use of some numpy foo for gradients
- Tests catch IncompleteRead errors.
Computes maximum curvature completeness on the non-cumulative distribution as it should be done.
#377 
=> Non cumulative maximum-curvature completeness

CHANGES.md, eqcorrscan/core/match_filter/helpers.py
Print seed-id that show which one of the traces has spike.
=> Add seed-id to the _spike_test's message.

eqcorrscan/utils/plotting.py
prevent raise error when there are only one trace and template to plot.
#397
=> legend's axis selected proper to number of axes in plot_repicked

eqcorrscan/core/match_filter/family.py, eqcorrscan/core/match_filter/party.py
Relative magnitudes on `Party` and `Family` requires more work.  This PR comments out the code and adds a static method stating that the method is no-longer functional.
#385
=> Remove relative magnitude methods for now, see issue #385

CHANGES.md, eqcorrscan/core/match_filter/family.py, eqcorrscan/core/match_filter/helpers.py, eqcorrscan/core/match_filter/party.py, eqcorrscan/core/match_filter/tribe.py, eqcorrscan/tests/match_filter_test.py
Adds monkey-patching of `get_waveforms_bulk` to a naive implementation a la Derrick.
#394 
=> Add monkey-patching to cope with clients without a `get_waveforms_bulk` method.

eqcorrscan/core/lag_calc.py, eqcorrscan/utils/catalog_to_dd.py
Changes travel-time format from 2dp to 4 dp.
=> Higher precision times in phase.dat

CHANGES.md, eqcorrscan/utils/mag_calc.py
Adds useful docs and changes to returning ints for integers rather than strings. This was very odd...
It was not clear that high "residuals" indicated good fit... Returning ints as strings is also very odd.
I haven't added a test for this. I probably should.
=> Freq mag docs

CHANGES.md, conftest.py, eqcorrscan/core/match_filter/party.py, eqcorrscan/tests/match_filter_test.py
Makes wildcard reading work for Party's
#387 - When using wildcards detections from multiple files, but the same family were not incorporated into the family (`=` rather than `+=`). This PR fixes this and adds a test.  @imankahbasi it would be great if you have time in the next day or so to try this out?
=> Test wildcards and ensure they work!

CHANGES.md, eqcorrscan/tutorials/lag_calc.py, eqcorrscan/utils/mag_calc.py
Sets use of `min_cc` regardless of whether `weight_by_correlation` is set.
#455 - this PR addresses part of this issue.  Whether weighting by correlation actually returns something useful or not is still up for discussion!
=> Use min_cc regardless.

CHANGES.md, eqcorrscan/core/match_filter/tribe.py, eqcorrscan/core/template_gen.py, eqcorrscan/tests/template_gen_test.py
Adds the ability to generate templates from any ol' object with a a get_waveforms method. This is useful for using EQCorrScan with ObsPlus.
#454
=> implement #454

.github/test_conda_env.yml, .github/test_conda_env_macOS.yml, setup.py
Updates setup to get EQcorrscan installable on github actions again
Tests do not run because EQcorrscan can't be installed.
=> Update installation for test running

eqcorrscan/utils/lib/__init__.py, setup.py
Remove `from future` imports.
Python 2.x is no longer supported, and these should have been removed when that support was removed, but a few were missed.
=> Remove future imports

eqcorrscan/core/template_gen.py, eqcorrscan/tests/template_gen_test.py
Copes with missing phase-hints in picks.
#470 #479
=> Missing phase hints

eqcorrscan/utils/libnames.py
Checks for all possible libname extensions for system when loading library.
#499
=> Properly check for libname extensions

eqcorrscan/core/subspace.py
Updates multiplex to avoid deprecated behavior in numpy stacking of ragged data.
Failing tests.
=> Subspace multiplex

.github/workflows/runtest.yml
codecov uploads have been failing, we should try updating the action.
Makes the codecov action less specific in an attempt to let codecov uploads work...
Codecov uploads keep failing.
=> More flexible codecov action version
