eqcorrscan/core/match_filter.py
Should the pick time be just the detect time and not detecttime + template start time - detect time (which I think is just template start time)?
Since plotting the events in catalog will trim to around the pick time.  So choosing the template start time as pick time doesn't cut the stream around where the actual detection was?
=> pick time to output to catalog

eqcorrscan/core/subspace.py, eqcorrscan/tests/subspace_test.py
This pr allows testing to work with either SciPy 0.18.x or 0.19.x, and also adds a warning to the `subspace.Detector` class doc-string.
This is to get around an issue resulting from an internal change in `scipy.linalg.svd`, which results in some sign changes in output.
=> Patch subspace for scipy 0.19.x

eqcorrscan/core/match_filter.py
Bug-fix: If data were missing for multiple templates, the routine to remove empty templates from the list of templates would break.
=> Patch template removal if empty

eqcorrscan/core/match_filter.py
Issue noted by user with low memory machine - crashes when extracting detection streams from the continuous data.  Suggest change from copying long data and trimming the copy, to slicing the continuous data and then copying the slice - this *should* reduce memory consumption.
=> Reduce memory consumption - det extraction

eqcorrscan/tests/lag_calc_test.py
For some reason test_bad_interp only raises one warning on travis, but two locally - attempt to debug
=> Debug failing lag_calc test

eqcorrscan/tests/match_filter_test.py
Adding bogus Family from scratch to original test_party_add function. Not sure if this is the cleanest way to do it....but it was the first that came to mind.
=> add new family to test_party_add() to ensure none are skipped

eqcorrscan/core/match_filter.py
This PR changes `eqcorrscan.core.match_filter.Tribe.client_detect` to return the whole stream used for the detection run if `return_stream` is set to True.  I think this is the expected behaviour, but it will lead to large amounts of memory being taken up if the users is not careful.
=> Append streams when return_stream == True

eqcorrscan/core/match_filter.py, eqcorrscan/tests/match_filter_test.py
This PR automatically includes overlaps in the `Tribe.detect` method for streams longer than one `process_length`.  This will combat missed detections at start and end of streams of data, which are inherent due to the delay-and-stack method of cross-correlation sum calculation.
=> Include overlap in .detect method

eqcorrscan/utils/mag_calc.py
Previous test for max curv relied on downloaded data, which appears to have changed.  This updated test relies on set data with a clear expected result.
=> Have a proper test for max curv

setup.py
Needed to ensure that numpy.flip is present, introduced in version 1.12.0
=> Add numpy minimum requirement

CHANGES.md, eqcorrscan/core/match_filter.py
Using trim method in _group_process destroys the stream for n_chunks > 1.
=> Change trim to slice to preserve trace

pytest.ini
This **PR** is to test the enabling of [Stickler.ci](https://stickler-ci.com/), and remove pep8 tests from travis and appveyor (because these should be taken care of by Stickler).
This closes #124
=> Don't make pep8 tests run during pytest.

CHANGES.md, eqcorrscan/core/lag_calc.py, eqcorrscan/core/match_filter.py, eqcorrscan/tests/lag_calc_test.py, eqcorrscan/tests/match_filter_test.py
This PR relates to issue #126 regarding `eqcorrscan.core.lag_calc.lag_calc`. When using multiple templates, LagCalcErrors are raised, when for the same templates and stream, running templates individually does not raise such an error.  The following (large - need to generate a smaller tests-case) results in the error:
```python
from eqcorrscan.core.match_filter import Tribe
from eqcorrscan.utils.catalog_utils import filter_picks
from eqcorrscan.utils.plotting import (pretty_template_plot,
detection_multiplot)
from obspy.clients.fdsn import Client
from obspy import UTCDateTime
client = Client('NCEDC')
t1 = UTCDateTime(2004, 9, 28)
t2 = t1 + 86400
catalog = client.get_events(
starttime=t1, endtime=t2, minmagnitude=2.5, minlatitude=35.7,
maxlatitude=36.1, minlongitude=-120.6, …
```
=> Lag-calc method for multiple templates sometimes gives the wrong answer.

CHANGES.md, codecov.yml, eqcorrscan/core/match_filter.py, eqcorrscan/tests/match_filter_test.py
This PR adds support for extracting a Template from a Tribe by the name of the template, and similarly, extracting a Family from a Party by the name of the template.
Closes #122
=> Add support for indexing by template-name

.travis.yml, CHANGES.md, codecov.yml, eqcorrscan/__init__.py, eqcorrscan/core/lag_calc.py, eqcorrscan/core/match_filter.py, eqcorrscan/lib/multi_corr.c, eqcorrscan/tests/correlate_test.py, eqcorrscan/tests/lag_calc_test.py, eqcorrscan/tests/match_filter_test.py, pytest.ini
This PR serves to update master prior to a 0.2.5 patch release.
These changes:
- fix a couple of small bugs that affect edge-cases where data are downloaded in funky lengths
- provide a properly normalised time-domain cross-correlation routine (which isn't fast for large cases, but is for small cases)
- allow slicing of match-filter objects by template-name.
Once this is merged a releases need to be created:
=> Prep for patch 0.2.5

eqcorrscan/doc/conf.py
Will need to enable building this branch and check that all docs pages are present - mostly relevant (or known to be missing) are:
=> Try to debug missing docs

setup.py
This should address #141 by way of removing the build directory before running any of the setup commands.
closes #141
=> Remove build directory to force rebuilding

.circleci/config.yml, eqcorrscan/doc/submodules/utils.correlate.rst, eqcorrscan/doc/submodules/utils.findpeaks.rst, eqcorrscan/doc/tutorials/clustering.rst, eqcorrscan/doc/tutorials/mag-calc.rst, eqcorrscan/doc/tutorials/matched-filter.rst, eqcorrscan/doc/tutorials/subspace.rst, eqcorrscan/doc/tutorials/template-creation.rst, eqcorrscan/utils/correlate.py, eqcorrscan/utils/mag_calc.py
Fixes #142 
This pull request reformats the appropriate doc-strings so that py.test will find them and run them.  I have set it up so that these get run on circleci, some are slow (network) tests, so running them there should result in less slow-don for other ci services.
I will need to build the docs on readthedocs and check that everything renders properly:
=> Doctest examples

CHANGES.md, appveyor.yml, eqcorrscan/lib/multi_corr.c
This should patch multi_corr.c to use a more available nan checker.  This should also run tests using multiple compilers on Windows now.
**This will require a 0.2.7 patch release.**
As such, on merge #160 needs to be re-rendered to 0.2.7 and everything done again.
=> use _isnan and test on MSCV 14

eqcorrscan/lib/multi_corr.c, eqcorrscan/tests/correlate_test.py, eqcorrscan/tests/match_filter_test.py, eqcorrscan/utils/libnames.py, setup.py
Closes #163 
This branch changes from using double precision for extended templates and images (and cross-correlations) to using single-precision floats. It also changes to using the fftwf functions and fftwf_complex numbers.
Tests pass locally on my OSX machine - need to compare memory usage...
=> Use floats instead of doubles

eqcorrscan/lib/time_corr.c
Memory for the running mean is allocated in the C function for time-domain corr-correlation, but never free-ed, resulting in an annoying memory leak. This PR adds free-ing to both serial and parallel functions.
=> Fix memory leak in time-domain

.travis.yml, setup.py
This PR adds a check for 64-bit ARM architecture.  Previously only 32-bit ARM arch was covered.
Adding this allows compilation of C routines on 64-Bit ARM chips (such as Odroid C2), all it does is omit the `-msse2` compile flag for ARM architectures.
=> Add check for Odroid C2 board

CHANGES.md, README.md, eqcorrscan/core/match_filter.py, eqcorrscan/doc/intro.rst, eqcorrscan/lib/multi_corr.c, eqcorrscan/tests/correlate_test.py, eqcorrscan/utils/correlate.py
Fixes #181.
This PR changes the `acceptedDiff` value in the fftw correlation backend to a smaller value (the smallest acceptable without incorrectly converting correlations to float) to allow data with lower variance to be used.
It also introduces a warning to explicitly show the user if the variance is below this level.
A test is also added with low amplitudes that previously failed and now does not.
=> Patch low amplitudes

CHANGES.md, eqcorrscan/core/match_filter.py, eqcorrscan/tests/match_filter_test.py
This PR changes `eqcorrscan.core.match_filter._group_process` to check whether any processing actually needs to be done, and if not, then it will return the stream input.
=> Do not do unnecesary processing

CHANGES.md, conftest.py, eqcorrscan/utils/plotting.py
This PR fixes #179 
This sets a maximum allowable length in points for the match-filter internal plotting, and runs a while loop to decimate until this is reached.
There is no test for this because plotting is not yet tested.
=> Change decimation strategy

eqcorrscan/__init__.py
This PR adds a few more commonly used convenience imports to the top of the eqcorrscan namespace.
It adds:
- eqcorrscan.core.match_filter
- match_filter, Detection, Party, Tribe, Family, Template
- eqcorrscan.core.subspace
- Detector, read_detector
- eqcorrscan.core.lag_calc
- lag_calc
- eqcorrscan.utils.correlate
- get_stream_xcorr, get_array_xcorr
This PR closes #155 
I will leave this open for a couple of days - if anyone wants anything else in here let me know and I can add it.
=> Add convenience imports

eqcorrscan/core/match_filter.py, eqcorrscan/tests/match_filter_test.py
This fixes a bug where detections below the threshold were not correctly removed in the `rethreshold` method. Looks like the `remove` method on lists in Python is unreliable, or doesn't do what I expect it to do.
This PR needs a test.
=> In core.match_filter.party.rethreshold, do not use list.remove

eqcorrscan/doc/installation.rst
Closes #198 
Adds install docs for MacPorts installs, and adds information on building against MKL.
=> Add MacPorts install docs

eqcorrscan/doc/submodules/core.match_filter.Template.rst, eqcorrscan/doc/submodules/core.match_filter.Tribe.rst, eqcorrscan/doc/submodules/core.match_filter.rst, eqcorrscan/doc/submodules/utils.correlate.rst, eqcorrscan/doc/submodules/utils.pre_processing.rst, eqcorrscan/utils/correlate.py, eqcorrscan/utils/src/multi_corr.c
This PR implements option 2 from #203.  Users are warned when the variance of the data is worryingly low (not non-zero) because this might be due to gaps padded after filtering. This copes with a change in behaviour from 0.2.7.
=> Warn when variance is low, and add docs

eqcorrscan/core/match_filter.py, eqcorrscan/utils/findpeaks.py
Find-peaks runs into memory assignment errors when the number of processes is large (on my machine, 80). This PR implements the `cores` kwarg for multi_find_peaks.
=> Add cores argument to find_peaks

CHANGES.md, eqcorrscan/core/match_filter.py, eqcorrscan/utils/findpeaks.py
This PR adds a `cores` kwarg to `eqcorrscan.utils.findpeaks.multi_find_peaks` to limit CPU usage.
This became an issue with not being able to allocate enough memory on an 80 CPU multi-core machine.
=> Add limits to findpeaks parallel processing

CHANGES.md, eqcorrscan/core/match_filter.py, eqcorrscan/core/template_gen.py, eqcorrscan/tests/match_filter_test.py, eqcorrscan/tests/pre_processing_test.py, eqcorrscan/tests/template_gen_test.py, eqcorrscan/utils/debug_log.py, eqcorrscan/utils/pre_processing.py, requirements.txt, setup.py
Patches a few `from_client` methods that were annoying.
1. Do not error when downloaded data are not long enough, just don't use them;
2. Allow multiple `swin` arguments so that both P and S phase templates can be created in one go;
3. Add ability to save progress on long-running methods (needs checking).
Downloading data when a station went offline caused an error. This is fine if you have the data locally, but if it's coming from a client you can't do anything about it. So, now if data downloaded would result in an error, those channels are dropped and the user is warned.
=> Patch client methods

eqcorrscan/core/template_gen.py, eqcorrscan/tests/template_gen_test.py
Adds back in the data-pad option for catalog grouping.
Data downloaded did not encompass events.
=> Use data-pad when grouping events

CHANGES.md, eqcorrscan/core/match_filter.py, eqcorrscan/core/template_gen.py, eqcorrscan/tests/match_filter_test.py
Closes #224 
The gap threshold seemed a little arbitrary and very short. @nackerley pointed this out when working on his own data and making his own method that allowed him to take data from multiple clients. Tests pass locally, but I haven't done anything special.
This needs:
~~- [x] A test with known gappy data to ensure that we don't get warnings of low variance from the underlying C-code~~
~~- [ ] Make a test that actually captures that output, or pass it back to Python properly...~~
These are handled by the `correlate.py` function now (see #230)
=> Remove gap threshold

eqcorrscan/core/match_filter.py, eqcorrscan/tests/match_filter_test.py
Adds and assertion to `Detection.__init__` that if the type of detection is `"corr"` then the correlation sum must be less than or equal to the number of channels.
The fails in #248 were associated with over-estimating the correlation sum - I still haven't worked this out, and can't replicate on my machine, but this will at least fail things closer to the source.
=> Assertion that correlation sum less than the number of channels

CHANGES.md, eqcorrscan/core/template_gen.py
Changes the behaviour of `template_gen` (and therefore `Tribe.construct`) for data that are day-long length, but do not start at the start of a day.  Previously data that started at say 5pm, were padded to start at midnight (17 hours before), and trimmed at the end of the day.  I'm fairly sure this isn't what anyone would want.
Now the data are checked to work out if the data actually do start near a day-break and then uses dayproc, otherwise it uses shortproc, which is a touch slower, but doesn't enforce as much.
=> Do not force day cuts

.travis.yml, appveyor.yml
Pins numpy to version 1.14 for travis and appveyor testing - it looks like 1.15.0 isn't working from conda at the moment for us for [Python < 3.6](https://travis-ci.org/eqcorrscan/EQcorrscan/jobs/409690060).
Note that if this works, then an issue should be raised at numpy, and, once fixed, this pin should be removed.
If it doesn't fix the tests, then who knows?
=> pin numpy to v.1.14

.travis.yml, eqcorrscan/core/match_filter.py, eqcorrscan/doc/tutorials/subspace.rst, eqcorrscan/tests/match_filter_test.py
Fixes some failing tests - pytest 3.7.1 changed behaviour and would not find test if referenced exactly, so that is changed, and `_spike_test(st)` was in the wrong place in `match_filter`.
No substantive code changes.
=> Fix failing tests

.travis.yml, CHANGES.md, eqcorrscan/core/match_filter.py, eqcorrscan/core/template_gen.py, eqcorrscan/tests/correlate_test.py, eqcorrscan/tests/match_filter_test.py, eqcorrscan/utils/src/multi_corr.c, setup.py
* Enforce pre-processing even when no filters or resampling is to be done to ensure gaps are properly processed (when called from `Tribe.detect`, `Template.detect` or `Tribe.client_detect`)
* BUG-FIX in `Tribe.client_detect` where data were processed from data  one sample too long resulting in minor differences in data processing (due to difference in FFT length) and therefore minor differences   in resulting correlations (~0.07 per channel).
Tests were sporadically failing when different lengths of data were download on the CI systems.
=> Patch process-len gaps for client_detect

CHANGES.md, eqcorrscan/core/template_gen.py, eqcorrscan/utils/pre_processing.py
Copes with one the less than one-sample before day start for start times of GeoNet data - this is handled, but the order got muddled in 0.3.2 and shortproc was used rather than dayproc.
Shortproc also now clips based on set start and end times.
=> shortproc clip and dayproc one sample

CHANGES.md, eqcorrscan/core/match_filter.py, eqcorrscan/tests/match_filter_test.py
Sets `Family.catalog` as a property, based on the detections in the Family.  It also alters how object addition is done.  Previously this was done inplace for both `+` and `+=`, which is not how it should be.
#272 
=> Change Family.catalog to a property

setup.py
Changes C-flags to remove unsupported flags.
A cluster running redhat failed to compile EQcorrscan. Removing these Cflags and linking flags fixed things.
=> change C-flags for RedHat

CHANGES.md, eqcorrscan/core/match_filter/detection.py, eqcorrscan/core/template_gen.py, eqcorrscan/tests/match_filter_test.py, eqcorrscan/tests/pre_processing_test.py, eqcorrscan/utils/correlate.py, eqcorrscan/utils/plotting.py, eqcorrscan/utils/pre_processing.py
Removes extraneous looping in `utils.pre_processing._prep_for_correlation` to improve speed.
This function was becoming a bottleneck for large template sets.  For a test template set of 1900 waveforms with many different channels the old implementation was taking > 30 seconds.  I managed to get this down to around 5 seconds.  It's still slow, but better.  I played around with threading as well, but the cost of starting the threads seems to mean that speed-ups are minimal and sometimes it takes longer threaded than in serial.
=> Speedup correlation prep function

CHANGES.md, eqcorrscan/core/template_gen.py, eqcorrscan/tests/template_gen_test.py
Adds a `skip_short_channels` argument to `template_gen`.  This allows a user to provide data of unknown length to template_gen without an error occurring related to short data streams. This defaults to False to continue the old behaviour.
Using the `from_client` method, data can be downloaded from pre-continuous data times - this will allow `from_client` to ignore short, triggered traces and continue working.
=> Add skip_short_channels arg to template_gen

CHANGES.md, eqcorrscan/core/match_filter/__init__.py, eqcorrscan/core/match_filter/detection.py, eqcorrscan/core/match_filter/party.py, eqcorrscan/tests/lag_calc_test.py, eqcorrscan/tests/match_filter_test.py
Closes #298 - adds a `write_detections` function to `eqcorrscan.core.match_filter.detection` to streamline detection writing and fixes the `.write` method on `Detection` objects.
=> Stop detection writing writing the header multiple times

CHANGES.md, eqcorrscan/utils/plotting.py
Uses step-wise decimation for cccsum histogram in `_match_filter_plot`.
#179 
=> Decimate cccsum_hist properly to fix #179

CHANGES.md, CONTRIBUTORS.md, eqcorrscan/core/template_gen.py, eqcorrscan/utils/plotting.py
Found an issue when construct template with option "plotdir" or "save_progress" on windows10, which can't use special character on the filename. So I added string format "strftime("%Y-%m-%dT%H%M%S")" for the default output-filename.
Format output filename to fix conflict with special character on windows filename
https://github.com/eqcorrscan/EQcorrscan/issues/344
=> format the output-filename on template_gen.py

.stickler.yml, CHANGES.md, eqcorrscan/tests/mag_calc_test.py, eqcorrscan/utils/mag_calc.py
Fixes the bug found in #376.  This PR adds a simple synthetic test for accuracy for filtered an unfiltered data. This test has quite broad error bounds highlighting the inaccuracy of the method as written.
I also took the opportunity to rewrite the function to make the code less repetitive and cleaner. It still isn't perfect, but its better than the old cludge.
#376 highlighted that I was looking up the wrong gain by assuming that the lookup method used previously would get the correct gain for the digital filter, when in actual fact it is implemented for analogue filters.  This resulted in wildly inaccurate gains computed (often > 100x).  This was the source of an issue patched in development when amplitude were divided by 100. This hack has been removed.
~~- [ ] First time contributors …
=> Patch amp pick event

CHANGES.md, eqcorrscan/core/template_gen.py, eqcorrscan/tests/match_filter_test.py
Events outside of the data span were incorrectly returned by template_gen, resulting in `Tribe().construct` assigning the wrong event metadata to templates if the catalogue provided contained events outside the span of the stream provided.
Commit summary:
- Fix bug #381
- Needs test
#381 
=> Patch for #381 - only return events used.

CHANGES.md, eqcorrscan/core/template_gen.py, eqcorrscan/tests/mag_calc_test.py, eqcorrscan/utils/mag_calc.py
Adds `iaspei_standard` option for `amp_pick_event`. Also adds `filter_id` and `method_id` to `Pick` and `Amplitude` objects made by `amp_pick_event`.
[ObsPy issue #2609](https://github.com/obspy/obspy/issues/2609)
=> Add IASPEI standard option

.travis.yml, appveyor.yml
Add test-running for Python 3.8 prior to conda-forge building.  This PR will be an attempt to fix some failing tests as well.
Anaconda defaults to Python 3.8 for new environments now, but EQcorrscan is not built for Python 3.8.  We should build for 3.8, but we need to test first.
=> Add travis testing on Python 3.8

CHANGES.md, eqcorrscan/core/match_filter/matched_filter.py, eqcorrscan/tests/match_filter_test.py, eqcorrscan/tests/pre_processing_test.py
Allows `ignore_bad_data=True` flag to be used to ignore bad traces.
Currently if `ignore_bad_data=True` and traces less than 80% of the required length are found, data from these will be removed, however the stats for these traces remain.  Due to some sloppy hard-coding, data are trimmed to the length of the zeroth trace, which might be length 0. This PR checks if there are 0-length traces and removes those.
=> Zero length processed data

CHANGES.md, eqcorrscan/core/match_filter/party.py, eqcorrscan/tests/find_peaks_test.py, eqcorrscan/utils/findpeaks.py, eqcorrscan/utils/src/find_peaks.c, eqcorrscan/utils/src/libutils.def, eqcorrscan/utils/src/libutils.h
Adds the ability to set a maximum hypocentral separation for declustering.  This means that events that are detected close in time, but in different places can be retained.
I wanted this for RT-EQcorrscan, so I did it.
=> Add distance thresholding to declustering

CHANGES.md, eqcorrscan/core/lag_calc.py, eqcorrscan/core/match_filter/family.py, eqcorrscan/core/match_filter/party.py, eqcorrscan/tests/lag_calc_test.py
Added the ability of saving correlation data of the lag_calc as NumPy binary files.
It can be useful for exploration on selecting proper threshold according to data that used.
=> Saving correlation data as npy file in lag_calc

eqcorrscan/core/match_filter/tribe.py
Allows passing of pre-processed data to `Tribe.detect`.
I want to set up some workflows using futures, and pre-processing is an obvious step to allocate to futures.
=> Allow pre-processed data for tribe.detect

eqcorrscan/doc/installation.rst
This PR adds a python version to the command to create a conda environment in the installation doc. 
Default behavior initiates a conda environment with Python 3.9, which yields a conflict when installing EQcorrscan via conda with `conda install -c conda-forge eqcorrscan`:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
Specifications:
- eqcorrscan -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
Your python: python=3.9
```
- [N/A] Any new features or fixed regressions are be covered via new tests.
- [N/A] Any new or changed features have are fully documented.
- [N/A] Significant changes have been added to `CHANGES.md`.
=> add python version to conda environment creation

CHANGES.md, eqcorrscan/tests/mag_calc_test.py, eqcorrscan/utils/mag_calc.py, eqcorrscan/utils/plotting.py
Fix bug reported in #476 
@darren-tpk you could try this with your specific case if you'd like.
This fixes the bug related to using S-pick traces when these should be excluded. The solution includes that `_get_pick_for_station` in addition to the station code compares the channel code and that the traces only linked to S-picks are excluded at the beginning of the `relative_magnitude` function.
Two thoughts:
- do we have to accomodate that users may ever supply picks without channel specification (I think no)?
- is it confusing that the function `_get_pick_for_station` checks both station and channel code now, considering its name?
- ~~[ ] Any new or changed features have are fully documented.~~
- ~~[ ] First time contributors have added your name to `CONTRIBUTORS.md`.~~
=> Fix relative mag s picks

.github/test_conda_env.yml, .github/test_conda_env_macOS.yml, .github/test_condarc.yml, .github/workflows/runtest.yml, eqcorrscan/utils/clustering.py, eqcorrscan/utils/correlate.py, eqcorrscan/utils/findpeaks.py, eqcorrscan/utils/pre_processing.py, requirements.txt
Bumps minimum obspy verison to 1.3.0 to cope with numpy incompat: https://github.com/obspy/obspy/issues/2912
https://github.com/obspy/obspy/issues/2912
~~- [ ] `develop` base branch selected?~~
=> Bump obspy version to 1.3.0

eqcorrscan/doc/tutorials/mag-calc.rst, eqcorrscan/utils/mag_calc.py
Fixes a broken link to the Rubinstein & Ellsworth paper titled Precise Estimation of Repeating Earthquake Moment: Example from Parkfield, California.
To fix broken links in two files.
=> Fix broken link

CHANGES.md, eqcorrscan/core/lag_calc.py, eqcorrscan/core/match_filter/family.py, eqcorrscan/tests/lag_calc_test.py, eqcorrscan/utils/catalog_to_dd.py, setup.py
Replaces the CC-interpolation function that can be used for `lag_calc` and `catalog_to_dd` with a function that simply resamples the CC.
- CC-interpolation with `_xcorr_interp` "failed" (i.e., no improvement with interpolation) more often than maybe necessary. For the example data in the test, the new function fails to produce an improved CC with interpolation in only about 90 cases, while the previous one failed in about 150 cases. 
- `_xcorr_interp` had one specific weakness: it needs more than 2 samples with negative curvature to interpolate around the peak of the CC. If seismograms are filtered just below the Nyquist frequency (e.g., sampling rate 20 Hz and low-pass filter at 9.9 Hz) and contain plenty of high-frequency content just below the Nyquist frequency, then that criterion of …
=> Make CC-interpolation simpler & more robust

.github/workflows/runtest.yml, eqcorrscan/core/lag_calc.py, eqcorrscan/tests/find_peaks_test.py, eqcorrscan/tests/lag_calc_test.py
Includes prepick when calculating the start time of extracted windows for lag-calc.
When using templates with `prepick`s larger than `shift-len` in `lag_calc` the data extracted do not include the whole window that should be correlated, leading to reduced cccsum errors.
=> Include prepick in lag-calc data preparation.

CHANGES.md, eqcorrscan/core/match_filter/matched_filter.py
Fixes a minor bug where the `peak_cores` arg could be defined twice if it was explicitly passed to the `match_filter` stack.
=> Only update peak_cores arg if it is't given explicitly already

CHANGES.md, eqcorrscan/core/lag_calc.py
Fixes bug where minimum CC for a pick wasn't set correctly via `min_cc_from_mean_cc_factor` when the total correlation sum was negative.
See conversation in https://github.com/eqcorrscan/EQcorrscan/pull/493.
~- [ ] First time contributors have added your name to `CONTRIBUTORS.md`.~
=> Fix bug where min_cc for negative correlations

CHANGES.md, eqcorrscan/core/match_filter/detection.py, eqcorrscan/core/match_filter/family.py, eqcorrscan/core/match_filter/template.py
Make sure `family._uniq()` is called after `Template.detect`. Also makes `Detection` objects unhashable as [they should be](https://docs.python.org/3/reference/datamodel.html#object.__hash__).
#431  - note this doesn't address the speed bottleneck in `._uniq` - the method currently deployed is the fastest that I have tested on unhashable `Detection` objects. The biggest speed-up for this would be to make `Detection` object immutable and hashable. But then they wouldn't have the event flexibility that we need.
=> Uniq detections

CHANGES.md, eqcorrscan/utils/src/find_peaks.c
Fix segmentation fault when using `utils.find_peaks.decluster_distance_time` with more than 46340 detections (46341^2 --> int32 overflow for `distance_index` in `find_peaks.c/decluster_dist_time` and `find_peaks.c/decluster_dist_time_ll`).
Only `distance_index` was defined as `int`, while all other indices / lengths in the c-libraries are at least of type `long`. So I expect no negative side effects from this fix. Let me know if we need an explicit test for this.
Minimal working example to demonstrate the previous segmentation fault:
```python
import numpy as np
import ctypes
from eqcorrscan.utils.libnames import _load_cdll
limit = 46342
arr = np.zeros([limit, ], dtype='float32')
inds = np.arange(0, limit, dtype='int32')
distance_matrix = np.zeros([limit, limit], dtype='float32') …
```
=> Fix segmentation fault with distance decluster int32 limit

.github/test_conda_env.yml, .github/test_conda_env_macOS.yml
NCEDC changed their URL and this is fixed in obspy v 1.4.0
=> Bump obspy version for NCEDC tests

CHANGES.md, eqcorrscan/tests/catalog_to_dd_test.py, eqcorrscan/utils/catalog_to_dd.py
Consistently slices traces in `utils.catalog_to_dd.prepare_stream` according to the same convention that is applied in `utils.pre_processing`: When traces end up with `(extract_len * samp_rate) + 1` samples because the chosen start time falls exactly on the first sample, then we remove the first sample from the trace.
Consequences:
- There are more correlation results in dt.cc
- The correlation times in `dt.cc` remain the same.
- The normalized cross-correlation values can change by +/- 0.0001 (precision of values is 0.0001)
`utils.catalog_to_dd.write_correlations` was printing many warnings about insufficient data because some traces (those where the starttime did not coincide exactly with a sample) were 1 sample shorter than others.
I was a bit surprised we didn't catch this earlier... …
=> Bugfix: Consistent trace slicing length for catalog_to_dd._prepare_stream

CHANGES.md, eqcorrscan/core/match_filter/matched_filter.py
- `matched_filter._group_detect`: **30x speedup in handling detections**
- selecting detections by template name in big list can be slow via loop. Dict-lookup offers ~50x speedup
- adding `prepick` to many picks (e.g., 400k) is somewhat slow because of `UTCDateTime` overhead. ~4x speedup with adding to `pick.time.ns` directly.
Collecting / handling detections after a `matched_filter` run was getting slow for many detections and templates.
This PR contributes to the summary issue in https://github.com/eqcorrscan/EQcorrscan/issues/522
~- [ ] Any new features or fixed regressions are be covered via new tests.~
~- [ ] Any new or changed features have are fully documented.~
~- [ ] First time contributors have added your name to `CONTRIBUTORS.md`.~
=> Speedup 06: 30x speedup for _group_detect - handling detections

CHANGES.md, eqcorrscan/core/lag_calc.py, eqcorrscan/core/match_filter/detection.py, eqcorrscan/core/match_filter/template.py, eqcorrscan/utils/correlate.py, eqcorrscan/utils/pre_processing.py
-  4x / 100x speedup for trace selection in `detection`, `lag_calc`,  `pre_processing`
-  trace selection by trace id from a stream is still something that takes more time than it needs to when working with many thousand (100K?) traces, even after https://github.com/obspy/obspy/pull/2886.
- When a user doesn't need wildcard selection, than the simple selection function can be sped up by a factor of 4 compared to `obspy.stream.select` 
- For the time when the order of traces in a stream does not change and a lot of traces need to be selected from that stream, then it's possible to speed up the selection by a factor of ~100 with a dict-lookup - this is very relevant for the template preparation in `_prep_data_for_correlation`
This PR contributes to the summary issue in …
=> Speedup 04: quick trace selection

CHANGES.md, eqcorrscan/core/match_filter/matched_filter.py
Implements 2.5x speedup for MAD threshold calculation in `core.match_filter.matched_filter`.  With this PR, MAD thresholds can be calculated in parallel; with joblib this is already worth it with a relatively small dataset (> 15 cccsum or 2e7 values in cccsums).
This has a noticeable effect for larger datasets, e.g., for 2000 templates, this reduced MAD-calculation from 50 s to 20 s with 30 cores.
- Computing median is not a cheap operation for big arrays, even in numpy.
- I checked two other ways for speeding this up:
- full vectorization with numpy --> 30 % slower than serial list-comprehension
- parallelization with Pool --> 50% slower than serial
This PR contributes to the summary issue in https://github.com/eqcorrscan/EQcorrscan/issues/522
Examples for comparing serial and parallel …
=> Speedup 07: 2.5x speedup with parallel parallel median / MAD calculation

CHANGES.md, eqcorrscan/core/match_filter/family.py, eqcorrscan/core/match_filter/tribe.py
- `core.match_filter.family._uniq`: **1.9x speedup**
- retrieving the unique list of detections is quicker for many detections with `list(set)` (1.9x speedup for 43000 detections, fastest: 3.1 s), but 1.2x slower for small sets (e.g., 430 detections; 50 ms --> 27 ms).
- `core.match_filter.detect` - **1000x speed up for many calls to `family._uniq`**
-  using `family._uniq` in a loop over all families is still rather slow with `_uniq`. Checking tuples of `(detection.id, detection.detect_time, detection.detect_val)` with `numpy.unique` and avoiding a loop is 1000x faster.  From 752 s to <1 s for 82000 detections.
Retrieving unique detections for `matched_filter`-run was getting slower than needed when there are a lot of detections.
This PR contributes to the summary issue in …
=> Speedup 05: Retrieve unique detections in family and in `matched_filter`

CHANGES.md, eqcorrscan/core/match_filter/matched_filter.py, eqcorrscan/utils/pre_processing.py
- 3x speed up for function `preprocessing._prep_data_for_correlation`
- provides new functions `_quick_copy_trace` and `_quick_stream_copy` that are ~3x quicker for copying simple traces by avoiding a call to `copy.deepcopy` where that is not necessary. So it helps with traces that mostly contain data, but will not speed up copying as much for traces with attached response and longer history.
When a user has a big set of heterogeneous templates (i.e., many templates with different station setups), filling the templates with NaN-channels takes a long time (many copy-operations in serial). This PR speeds that process up by a factor of 3 in my example, going from ca. 150 s to 50 s for 1500 templates with up to 500 channels.
This PR contributes to the summary issue in …
=> Speedup 02: 3x speed up for prep_data_for_correlation with custom copy and trace-selection

CHANGES.md, eqcorrscan/utils/correlate.py, eqcorrscan/utils/pre_processing.py
Implements:
- 25 % speedup for `utils.correlate._get_array_dicts` (from 200 s to 154 seconds total time spent in my test)
- 10 % speedup for `utils.pre_processing._prep_data_for_correlation` (from 702 s to 640 s total time spent)
- (for comparison to the numbers above: 494 s were spent for correlating data in parallel on the GPU)
Main speedups with:
- direct operations on `UTCDateTime.__dict__['_UTCDateTime__ns']` (5x quicker for one +/- operation)
- index-based access to trace in stream with `stream.traces[j]` instead of `stream[j]` (4.5x quicker)
For big datasets run on powerful hardware, the cumulative time spent in `utils.correlate._get_array_dicts` and `utils.pre_processing._prep_data_for_correlation` makes up a considerable part (>50 %) of a detection run. This PR tries to optimize …
=> Speedup 10:  25 % quicker _get_array_dicts and 10 % quicker _prep_data_for_correlation

.readthedocs.yml, eqcorrscan/doc/requirements.txt
Updates the readthedocs config file to include a build section as now required
Readthedocs builds are currently failing.
*note:* this should be merged into develop as well.
=> Update .readthedocs.yml build config

eqcorrscan/core/match_filter/helpers/processes.py, eqcorrscan/core/match_filter/helpers/tribe.py, eqcorrscan/core/match_filter/tribe.py
Add option to not create events at detection time.
=> Optionally do not make events at detection time.

eqcorrscan/core/template_gen.py
See #563 - some picks from FDSN services are missing channel codes resulting in an opaque and hard to understand error.
Adds a useful error message when waveform_ids are incomplete when generating templates.
#563
=> Raise useful error when waveform_id is incomplete

eqcorrscan/utils/mag_calc.py
Adds the option to start magnitude picking windows from the P pick rather than the S.
When an S-pick is not present, the S-time is calculated (badly), which can lead to amplitude picking windows missing the body waves. Starting from the P pick is probably a better way to pick magnitude amplitudes as the definition of magnitudes is maximum body wave amplitude (usually).
=> Add option to pick from P pick

eqcorrscan/utils/pre_processing.py
As identified in #573 - the first sample is sometimes dropped and the starttime is not adjusted leading to one-sample-out errors. I don't know why that was left in and the tests pass if we drop the last sample instead.
#573
=> Drop last sample, not first

eqcorrscan/core/match_filter/detection.py, eqcorrscan/tests/lag_calc_test.py, eqcorrscan/tests/matched_filter/match_filter_test.py
As noted in #573 - lag-calc fails to run sometimes when slicing to particular lengths. This happens when the pick.time - pre_pick does not fall on a sample. Obspy will often slice to give a shorter window than needed. This PR now slices starting at the nearest sample before the pick.time - pre_pick to ensure that data are trimmed to within one sample of the requested length.
#573
=> Detection trim

eqcorrscan/tests/clustering_test.py, eqcorrscan/utils/catalog_to_dd.py, eqcorrscan/utils/clustering.py, eqcorrscan/utils/src/distance_cluster.c, eqcorrscan/utils/src/libutils.def
Computes distance between one event and a catalog of other events. This is essentially one column of the distance matrix.
I need this for work in RT-EQcorrscan to implement near real-time relocations, which requires the addition of single events to the correlations. This is one part of that process.
=> Add function to compute distance between one event and a catalog

CHANGES.md, eqcorrscan/core/match_filter/party.py, eqcorrscan/tests/matched_filter/match_filter_test.py
Implements a way to use lag-calc using data from a client.
It annoyed me that I didn't have this option!
=> Client lag-calc implementation

eqcorrscan/core/match_filter/party.py
Raises an assertion error if the wrong type is provided to Party on init
I frequently accidentally instantiate a party with a string. This should not be allowed.
~~- [ ] `develop` base branch selected?~~
=> Force Party instantiation to be made from Families

eqcorrscan/core/match_filter/family.py
Makes `Family.catalog` always get a fresh view of the events associated with detections.
#598 
=> Always get new catalog from detections #598
